### ISSUE TITLE
Use non-sequencial IDs as PK

### ISSUE THREAD

**Issue by mk2301** [FoodCoopX/wirgarten-tapir#16]
To improve security, I would opt to generate random IDs instead of using a sequence.
E.g. NanoID: https://github.com/puyuan/py-nanoid

The problems with sequences include the following:
- PKs can be easily guessed, e.g. in combination with wrong configured permissions users could see data they are not supposed to
- it exposes information about the dataset like number of entities (if you create a new account and get id "401", you know there are about 400 other user accounts)
- it exposes information about transaction rates (e.g. how many new users per day)
- in general it makes life easy for scripts and scrapers to guess URLs

We need to take security seriously as we manage sensible user data, and this would be an easy improvement.

**Comment by gkirchner** [comment]
I agree.
