### ISSUE TITLE
DevOps Story: Improve SonarQube integration with Github action

### ISSUE THREAD

**Issue by gkirchner** [FoodCoopX/wirgarten-tapir#17]
As DevOps or Product Owner I want to have a high quality app which has a good code quality and test coverage.

We can have our own SonarQube cloud instance for free (currently it is only setup for SuperCoopBerlin/Tapir) and need to find a way to include test automation into the CI pipeline with Github actions and integrate the test coverage results into the SonarQube dashboard.

Acceptance Criteria:
We have our own WirGarten-Tapir instance of SonarQube running.
Automated tests are running with each pipeline execution and test coverage is measured and included into the SonarQube dashboard.

Details:
SuperCoop-Tapir SonarQube instance: https://sonarcloud.io/project/overview?id=SuperCoopBerlin_tapir
Starting points for research:
https://docs.sonarqube.org/latest/analysis/test-coverage/python-test-coverage/
https://breadcrumbscollector.tech/how-to-use-code-coverage-in-python-with-pytest/

It might also be useful to check other Python code quality tools (codeql from Github e.g., Flake8) if they provide more value than SonarQube which is already a bit older and not originally created for Python.

**Comment by oliveratfoodcoopx** [comment]
@gkirchner I think, with the latest changes I pushed (related to CodeQL) and you last PR (to integrate SonarCloud) both seems to be integrated. do you mind checking this out?

**Comment by mk2301** [comment]
Please reopen if there is more discussion needed
