### ISSUE TITLE
Registration Wizard: For only investing members, the form doesn't redirect correctly

### ISSUE THREAD

**Issue by mk2301** [FoodCoopX/wirgarten-tapir#37]
If no harvest shares are selected, the wizard skips certain steps (chicken shares, BestellCoop, pickup location). 
After the last steps (consents) however, those skipped forms are shown to the user instead of the confirmation page.

Reproduce:
1. go to http://localhost:8000/wirgarten/register
2. don't select harvest shares (0 for all inputs)
3. click next until you reach the last step
4. click "Bestellung abschließen" 

**Expected**: you see the confirmation page
**Actual**: you see the chicken share page

**Comment by MarkWPeter** [comment]
Problem solved, found a way to use formtools wizard correctly, so custom behavior is possible (skipping steps).
-> usage of 'condition_dict' plus certain hook in functions.
Solved some other issues/bugs along the way (i.e. persisting data failed, if certain conditions weren't met.)
