### ISSUE TITLE
Delivery cycle per ProductType

### ISSUE THREAD

**Issue by mk2301** [FoodCoopX/wirgarten-tapir#43]
It must be possible to define a delivery cycle for each `ProductType`.

E.g. Harvest shares are delivered weekly, Chicken shares every 2 weeks. 

**DeliveryCycle(Enum)**
- NO_DELIVERY
- WEEKLY
- EVEN_WEEKS
- ODD_WEEKS
- MONTHLY

**ProductType**
- delivery_cycle: DeliveryCycle(Enum)
- ~pickup_enabled~ <-- remove field, DeliveryCycle.NO_DELIVERY should be used instead

**Comment by MarkWPeter** [comment]
implemented as described above. Updated Period/Product Config UI
