### ISSUE TITLE
Parameter View: ordering for parameters

### ISSUE THREAD

**Issue by mk2301** [FoodCoopX/wirgarten-tapir#47]
It might be useful to define an order for the parameters of a category. 

TBD

**Comment by MarkWPeter** [comment]
I will have a look into it, my first idea is to optionally provide the parameters with a priority attribute. 
The sorting method then should follow this logic:
if 'category' is the same 
    if no priority provided
        sort alphabetically (behind items with provided priority)
    else
        if (priority is NOT the same)
            sort by priority (with priority > no priority)
        else
            sort alphabetically (within those with provided priority)
sort by category

**Comment by MarkWPeter** [comment]
feature implemented.
TODO: document in README.md

**Comment by MarkWPeter** [comment]
DONE: document in README.md

**Comment by mk2301** [comment]
merged
