### ISSUE TITLE
Development Workflow + Quality Improvements

### ISSUE THREAD

**Issue by mk2301** [FoodCoopX/wirgarten-tapir#5]
To improve the quality of the repository, I would suggest the following:

- protect the master branch (so we can't commit directly onto it)
- use naming conventions for branches
  - `feature/#<github-issue>/<short-description>`
  - `bug/#<github-issue>/<short-description>`
- use naming convention for commit messages:
  - `#<github-issue>: <description>`
- run a CI pipeline before merge
  1) check dependencies for vulnerabilities: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
  2) python source code vulnerability scanning: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
  3) run migrations
  4) run tests
  5) check if the application starts and responds to a HTTP request
  --> only merge if everything passes

With that we would make sure that:
  - all changes to the master are traceable to a bug or feature
  - we don't introduce new vulnerabilities
  - tests are passing
  - the application starts successfully

**Comment by Theophile-Madet** [comment]
We already have some of your CI pipeline suggestions in the SuperCoop repo, they are not perfect but still a great help, I love having them. Feel free to get inspiration from our [.github/workflows](https://github.com/SuperCoopBerlin/tapir/tree/master/.github/workflows). 
We have codeql and tests. From a quick look at the doc our codeql stuff is be outdated. 
There is also some [rudimentary selenium tests](https://github.com/SuperCoopBerlin/tapir/blob/9a1bc75418443e71004b4762746639fe9621a481/tapir/accounts/tests/test_integration.py) that should make sure that the server starts and that login works.

I would not necessarily build and push the docker image on every merge, we only need do to that when we want to deploy. 

The conventions assume that every change has a corresponding issue. We haven't always had that until now, but I can see how the documentation benefits outweight the extra formalism.

**Comment by mk2301** [comment]
The pipline is working and I described the workflow in [CONTRIBUTING.md](https://github.com/FoodCoopX/wirgarten-tapir/blob/master/CONTRIBUTING.md#workflow)
