### ISSUE TITLE
Admin Story: The admin can configure whether Coop shares are subscribable independently to Harvest shares.

### ISSUE THREAD

**Issue by MarkWPeter** [FoodCoopX/wirgarten-tapir#62]
[see trello board](https://trello.com/c/oijW4zfu)

**Comment by MarkWPeter** [comment]
1. create parameter(boolean) within existing data structure. **coop_shares_independent_to_harvest_shares** ( location -> tapir/wirgarten/parameters.py ) 
2. makemigrate and migrate
3. implement the parameter as shown and editable value(boolean) in **admin view** / **dashboard**
4. implement in registration wizard as followed:

- if **coop_shares_independent_to_harvest_shares** provide form validation in harvest shares form and provide validation message/warning. validation checks for `user chose at least one product in one category == True`.

**Comment by mk2301** [comment]
2. not needed, you need to execute `manage.py parameter_definitions` instead

**Comment by MarkWPeter** [comment]
Thx, i corrected the statement

**Comment by MarkWPeter** [comment]
implemented as described above. With the addition, if harvest shares are currently not subscribable, the parameter is ignored for now, otherwise the further subscription process would be obsolete.

**Comment by mk2301** [comment]
>  if harvest shares are currently not subscribable, the parameter is ignored for now, otherwise the further subscription process would be obsolete

@MarkWPeter Please open a new issue for that (so we don't forget about it) and close this one afterwards :slightly_smiling_face:
