### ISSUE TITLE
Waiting list and wizard routing to it

### ISSUE THREAD

**Issue by MarkWPeter** [FoodCoopX/wirgarten-tapir#64]
Problem: 

If the Admin did set the following conditions....
- `HARVEST_SHARES_SUBSCRIBABLE` set to `False`
- `COOP_SHARES_INDEPENDENT_FROM_HARVEST_SHARES` set to `False`
...the registration wizard should not function at all, and rout to a page where the user can register themself for a waiting spot.

Right now the wizard ignores the `COOP_SHARES_INDEPENDENT_FROM_HARVEST_SHARES` parameter if the `HARVEST_SHARES_SUBSCRIBABLE` is set to `False`, so the registration process continues.

**Comment by mk2301** [comment]
done in #122
